version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox
workflows:
  version: 2
  test:
    jobs:
      - test
